font_size 10.0

cursor #47FF9C
cursor_text_color #011423
cursor_shape block


url_color #0087bd
url_style straight
visual_bell_duration 1.0 ease-in linear


foreground #CBE0F0
background #011423
background_opacity 0.9
background_blur 5
dynamic_background_opacity yes

# colors
color0 #214969
color8 #214969
color1 #E52E2E
color9 #E52E2E
color2  #44FFB1
color10 #44FFB1
color3  #FFE073
color11 #FFE073
color4  #0FC5ED
color12 #A277FF
color5  #a277ff
color13 #a277ff
color6  #24EAF7
color14 #24EAF7
color7  #24EAF7
color15 #24EAF7

# kitty fonts
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

# emojis
symbol_map U+1F000-U+1FFFF Noto Color Emoji

# CJK fallback
symbol_map U+2E80-U+2EFF Noto Sans CJK JP
symbol_map U+3000-U+30FF Noto Sans CJK JP
symbol_map U+31C0-U+31EF Noto Sans CJK JP
symbol_map U+3200-U+32FF Noto Sans CJK JP
symbol_map U+3300-U+33FF Noto Sans CJK JP
symbol_map U+4E00-U+9FFF Noto Sans CJK JP # Common CJK Unified Ideographs
symbol_map U+F900-U+FAFF Noto Sans CJK JP # CJK Compatibility Ideographs
symbol_map U+2F800-U+2FA1F Noto Sans CJK JP # CJK Compatibility Ideographs Supplement
