preload=~/.config/mac_wallpaper2.png
wallpaper {
    monitor = DP-3
    path = ~/.config/mac_wallpaper2.png
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/mac_wallpaper2.png
}

wallpaper {
    monitor =
    path = ~/.config/mac_wallpaper2.png
}

splash = false


